class CategoryFilterDefault < ::ApplicationRecord
  extend _ActiveRecord_Relation_ClassMethods[CategoryFilterDefault, ActiveRecord_Relation, Integer]

  module GeneratedAttributeMethods
    def id: () -> Integer

    def id=: (Integer) -> Integer

    def id?: () -> bool

    def id_changed?: () -> bool

    def id_change: () -> [ Integer?, Integer? ]

    def id_will_change!: () -> void

    def id_was: () -> Integer?

    def id_previously_changed?: () -> bool

    def id_previous_change: () -> Array[Integer?]?

    def id_previously_was: () -> Integer?

    def id_before_last_save: () -> Integer?

    def id_change_to_be_saved: () -> Array[Integer?]?

    def id_in_database: () -> Integer?

    def saved_change_to_id: () -> Array[Integer?]?

    def saved_change_to_id?: () -> bool

    def will_save_change_to_id?: () -> bool

    def restore_id!: () -> void

    def clear_id_change: () -> void

    def user_id: () -> Integer

    def user_id=: (Integer) -> Integer

    def user_id?: () -> bool

    def user_id_changed?: () -> bool

    def user_id_change: () -> [ Integer?, Integer? ]

    def user_id_will_change!: () -> void

    def user_id_was: () -> Integer?

    def user_id_previously_changed?: () -> bool

    def user_id_previous_change: () -> Array[Integer?]?

    def user_id_previously_was: () -> Integer?

    def user_id_before_last_save: () -> Integer?

    def user_id_change_to_be_saved: () -> Array[Integer?]?

    def user_id_in_database: () -> Integer?

    def saved_change_to_user_id: () -> Array[Integer?]?

    def saved_change_to_user_id?: () -> bool

    def will_save_change_to_user_id?: () -> bool

    def restore_user_id!: () -> void

    def clear_user_id_change: () -> void

    def filter_id: () -> Integer

    def filter_id=: (Integer) -> Integer

    def filter_id?: () -> bool

    def filter_id_changed?: () -> bool

    def filter_id_change: () -> [ Integer?, Integer? ]

    def filter_id_will_change!: () -> void

    def filter_id_was: () -> Integer?

    def filter_id_previously_changed?: () -> bool

    def filter_id_previous_change: () -> Array[Integer?]?

    def filter_id_previously_was: () -> Integer?

    def filter_id_before_last_save: () -> Integer?

    def filter_id_change_to_be_saved: () -> Array[Integer?]?

    def filter_id_in_database: () -> Integer?

    def saved_change_to_filter_id: () -> Array[Integer?]?

    def saved_change_to_filter_id?: () -> bool

    def will_save_change_to_filter_id?: () -> bool

    def restore_filter_id!: () -> void

    def clear_filter_id_change: () -> void

    def category_id: () -> Integer

    def category_id=: (Integer) -> Integer

    def category_id?: () -> bool

    def category_id_changed?: () -> bool

    def category_id_change: () -> [ Integer?, Integer? ]

    def category_id_will_change!: () -> void

    def category_id_was: () -> Integer?

    def category_id_previously_changed?: () -> bool

    def category_id_previous_change: () -> Array[Integer?]?

    def category_id_previously_was: () -> Integer?

    def category_id_before_last_save: () -> Integer?

    def category_id_change_to_be_saved: () -> Array[Integer?]?

    def category_id_in_database: () -> Integer?

    def saved_change_to_category_id: () -> Array[Integer?]?

    def saved_change_to_category_id?: () -> bool

    def will_save_change_to_category_id?: () -> bool

    def restore_category_id!: () -> void

    def clear_category_id_change: () -> void
  end
  include GeneratedAttributeMethods

  def user: () -> User
  def user=: (User?) -> User?
  def reload_user: () -> User?
  def build_user: (untyped) -> User
  def create_user: (untyped) -> User
  def create_user!: (untyped) -> User
  def filter: () -> Filter
  def filter=: (Filter?) -> Filter?
  def reload_filter: () -> Filter?
  def build_filter: (untyped) -> Filter
  def create_filter: (untyped) -> Filter
  def create_filter!: (untyped) -> Filter
  def category: () -> Category
  def category=: (Category?) -> Category?
  def reload_category: () -> Category?
  def build_category: (untyped) -> Category
  def create_category: (untyped) -> Category
  def create_category!: (untyped) -> Category
  module GeneratedAssociationMethods
  end
  include GeneratedAssociationMethods

  module GeneratedRelationMethods
  end

  class ActiveRecord_Relation < ::ActiveRecord::Relation
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[CategoryFilterDefault, Integer]
    include Enumerable[CategoryFilterDefault]
  end

  class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
    include GeneratedRelationMethods
    include _ActiveRecord_Relation[CategoryFilterDefault, Integer]
  end
end
