class Category < ::ApplicationRecord
  class HABTM_RequiredTags < ::ActiveRecord::Base
    extend _ActiveRecord_Relation_ClassMethods[Category::HABTM_RequiredTags, ActiveRecord_Relation, top]

    module GeneratedAttributeMethods
      def category_id: () -> Integer?

      def category_id=: (Integer?) -> Integer?

      def category_id?: () -> bool

      def category_id_changed?: () -> bool

      def category_id_change: () -> [ Integer?, Integer? ]

      def category_id_will_change!: () -> void

      def category_id_was: () -> Integer?

      def category_id_previously_changed?: () -> bool

      def category_id_previous_change: () -> Array[Integer?]?

      def category_id_previously_was: () -> Integer?

      def category_id_before_last_save: () -> Integer?

      def category_id_change_to_be_saved: () -> Array[Integer?]?

      def category_id_in_database: () -> Integer?

      def saved_change_to_category_id: () -> Array[Integer?]?

      def saved_change_to_category_id?: () -> bool

      def will_save_change_to_category_id?: () -> bool

      def restore_category_id!: () -> void

      def clear_category_id_change: () -> void

      def tag_id: () -> Integer?

      def tag_id=: (Integer?) -> Integer?

      def tag_id?: () -> bool

      def tag_id_changed?: () -> bool

      def tag_id_change: () -> [ Integer?, Integer? ]

      def tag_id_will_change!: () -> void

      def tag_id_was: () -> Integer?

      def tag_id_previously_changed?: () -> bool

      def tag_id_previous_change: () -> Array[Integer?]?

      def tag_id_previously_was: () -> Integer?

      def tag_id_before_last_save: () -> Integer?

      def tag_id_change_to_be_saved: () -> Array[Integer?]?

      def tag_id_in_database: () -> Integer?

      def saved_change_to_tag_id: () -> Array[Integer?]?

      def saved_change_to_tag_id?: () -> bool

      def will_save_change_to_tag_id?: () -> bool

      def restore_tag_id!: () -> void

      def clear_tag_id_change: () -> void
    end
    include GeneratedAttributeMethods

    def left_side: () -> Category?
    def left_side=: (Category?) -> Category?
    def reload_left_side: () -> Category?
    def build_left_side: (untyped) -> Category
    def create_left_side: (untyped) -> Category
    def create_left_side!: (untyped) -> Category
    def required_tag: () -> Tag?
    def required_tag=: (Tag?) -> Tag?
    def reload_required_tag: () -> Tag?
    def build_required_tag: (untyped) -> Tag
    def create_required_tag: (untyped) -> Tag
    def create_required_tag!: (untyped) -> Tag
    module GeneratedAssociationMethods
    end
    include GeneratedAssociationMethods

    module GeneratedRelationMethods
    end

    class ActiveRecord_Relation < ::ActiveRecord::Relation
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[Category::HABTM_RequiredTags, top]
      include Enumerable[Category::HABTM_RequiredTags]
    end

    class ActiveRecord_Associations_CollectionProxy < ::ActiveRecord::Associations::CollectionProxy
      include GeneratedRelationMethods
      include _ActiveRecord_Relation[Category::HABTM_RequiredTags, top]
    end
  end
end
