# This file is maintained in alphabetic order by class name (Layout, Metrics, Style) first, then by key name.

require:
  - ./lib/rubocop/path_in_helpers.rb

AllCops:
  TargetRubyVersion: 3.1
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'scripts/**/*'
    - 'bin/**/*'
    - 'lib/namespaced_env_cache.rb'
    - 'vendor/bundle/**/*'
  NewCops: enable
  SuggestExtensions: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Max: 120
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/PathInHelpers:
  Enabled: true
  Include:
    - app/helpers/**/*.rb
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Max: 30
Metrics/BlockNesting:
  Max: 5
Metrics/ClassLength:
  Max: 350
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/MethodLength:
  Max: 60
Metrics/ModuleLength:
  Max: 250
Metrics/PerceivedComplexity:
  Enabled: false

Naming/BlockForwarding:
  EnforcedStyle: explicit
Naming/PredicateMethod:
  Mode: conservative
  AllowedPatterns: ['verify_.*', 'check_.*', 'enforce_.*', 'setup_.*']
  AllowedMethods:
    - post_sign_in # returns a boolean but is a necessary after-sign-in method for both normal and SAML flows
    - comment_rate_limited? # returns a tuple with the boolean as the first value
  AllowBangMethods: true

Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false  # No need for specific documentation comments, but please add inline comments where necessary.
Style/DoubleNegation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: never
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
