# This file is maintained in alphabetic order by class name (Layout, Metrics, Style) first, then by key name.

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'scripts/**/*'
    - 'bin/**/*'

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true
Layout/HashAlignment:
  Enabled: false
Layout/LineLength:
  Max: 120
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Max: 30
Metrics/ClassLength:
  Max: 300
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 200
Metrics/PerceivedComplexity:
  Max: 15

Style/ClassAndModuleChildren:
  Enabled: false
Style/ClassVars:
  Enabled: false
Style/Documentation:
  Enabled: false  # No need for specific documentation comments, but please add inline comments where necessary.
Style/DoubleNegation:
  Enabled: false
Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IfInsideElse:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
