version: "3.8"
services:
  db:
    build:
      context: "."
      dockerfile: docker/Dockerfile.db
    volumes:  
      - ./docker/mysql:/var/lib/mysql
    env_file:
      - ${ENV_FILE_LOCATION}
    command: mysqld --default-authentication-plugin=mysql_native_password --skip-mysqlx

  uwsgi:
    restart: always
    build:
      context: "."
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    environment:
      - COMMUNITY_NAME=${COMMUNITY_NAME}
      - RAILS_ENV=${RAILS_ENV}
      - CONFIRMABLE_ALLOWED_ACCESS_DAYS=${CONFIRMABLE_ALLOWED_ACCESS_DAYS}
    env_file:
      - ${ENV_FILE_LOCATION}
    ports:
      - "${LOCAL_DEV_PORT}:3000"
    volumes:
      - .:/code
      - ./static:/var/www/static
      - ./images:/var/www/images
    links:
      - redis
      - db

  redis:
    restart: always
    image: redis:latest
    depends_on:
      - db
