services:
  db:
    build:
      context: "."
      dockerfile: docker/Dockerfile.db
    volumes:
      - ./docker/mysql:/var/lib/mysql
    env_file:
      - ${ENV_FILE_LOCATION}
    command: mysqld --mysql-native-password=on --skip-mysqlx
    cap_add:
      - SYS_NICE
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 12


  uwsgi:
    restart: always
    build:
      context: "."
      dockerfile: docker/Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - COMMUNITY_NAME=${COMMUNITY_NAME}
      - RAILS_ENV=${RAILS_ENV}
      - CONFIRMABLE_ALLOWED_ACCESS_DAYS=${CONFIRMABLE_ALLOWED_ACCESS_DAYS}
      - LOCAL_DEV_PORT=${LOCAL_DEV_PORT}
    env_file:
      - ${ENV_FILE_LOCATION}
    ports:
      - "${LOCAL_DEV_PORT}:3000"
    volumes:
      - .:/code
      - ./static:/var/www/static
      - ./images:/var/www/images
    links:
      - redis
      - db

  redis:
    restart: always
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
