class ApplicationRecord < ActiveRecord::Base
end
class Post::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Vote::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Notification::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Subscription::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CommunityUser::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Flag::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ErrorLog::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class SuggestedEdit::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class AuditLog::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ModWarning::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Comment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CommentThread::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CategoryFilterDefault::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Filter::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PostHistory::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Reaction::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class CategoryPostType::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Category::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PostType::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ThreadFollower::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class SiteSetting::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class UserAbility::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class PostHistoryTag::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class Tag::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class TagWithPath < Tag
end
class TagWithPath::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class TagSynonym::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module MicroAuth
end
class MicroAuth::Token::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class User::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
module ActiveStorage
end
class ActiveStorage::Record < ActiveRecord::Base
end
class ActiveStorage::VariantRecord::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ActiveStorage::Attachment::ActiveRecord_Associations_CollectionProxy < ActiveRecord::Associations::CollectionProxy
end
class ActiveRecord::Associations::CollectionProxy < ActiveRecord::Relation
end
class ActiveRecord::Relation < Object
end
module ActiveRecord::Associations
end
