interface _RbsRailsPathHelpers
  def rails_mailers_path: (*untyped) -> String
  def rails_info_properties_path: (*untyped) -> String
  def rails_info_routes_path: (*untyped) -> String
  def rails_info_path: (*untyped) -> String
  def new_user_session_path: (*untyped) -> String
  def user_session_path: (*untyped) -> String
  def destroy_user_session_path: (*untyped) -> String
  def new_user_password_path: (*untyped) -> String
  def edit_user_password_path: (*untyped) -> String
  def user_password_path: (*untyped) -> String
  def cancel_user_registration_path: (*untyped) -> String
  def new_user_registration_path: (*untyped) -> String
  def edit_user_registration_path: (*untyped) -> String
  def user_registration_path: (*untyped) -> String
  def new_user_confirmation_path: (*untyped) -> String
  def user_confirmation_path: (*untyped) -> String
  def new_user_unlock_path: (*untyped) -> String
  def user_unlock_path: (*untyped) -> String
  def new_saml_user_session_path: (*untyped) -> String
  def saml_user_session_path: (*untyped) -> String
  def destroy_saml_user_session_path: (*untyped) -> String
  def metadata_user_session_path: (*untyped) -> String
  def idp_destroy_saml_user_session_path: (*untyped) -> String
  def login_verify_2fa_path: (*untyped) -> String
  def login_verify_code_path: (*untyped) -> String
  def sign_in_request_from_other_path: (*untyped) -> String
  def sign_in_return_from_base_path: (*untyped) -> String
  def after_sign_in_check_path: (*untyped) -> String
  def root_path: (*untyped) -> String
  def letter_opener_web_path: (*untyped) -> String
  def admin_path: (*untyped) -> String
  def admin_error_reports_path: (*untyped) -> String
  def site_settings_path: (*untyped) -> String
  def global_settings_path: (*untyped) -> String
  def site_setting_path: (*untyped) -> String
  def update_site_setting_path: (*untyped) -> String
  def soft_delete_user_path: (*untyped) -> String
  def admin_privileges_path: (*untyped) -> String
  def admin_privilege_path: (*untyped) -> String
  def admin_update_privilege_path: (*untyped) -> String
  def moderator_email_path: (*untyped) -> String
  def send_moderator_email_path: (*untyped) -> String
  def email_all_path: (*untyped) -> String
  def send_all_email_path: (*untyped) -> String
  def audit_log_path: (*untyped) -> String
  def new_site_path: (*untyped) -> String
  def create_site_path: (*untyped) -> String
  def setup_path: (*untyped) -> String
  def setup_save_path: (*untyped) -> String
  def stop_impersonating_path: (*untyped) -> String
  def verify_elevation_path: (*untyped) -> String
  def impersonate_path: (*untyped) -> String
  def start_impersonating_path: (*untyped) -> String
  def post_types_path: (*untyped) -> String
  def new_post_type_path: (*untyped) -> String
  def create_post_type_path: (*untyped) -> String
  def edit_post_type_path: (*untyped) -> String
  def update_post_type_path: (*untyped) -> String
  def close_reasons_path: (*untyped) -> String
  def close_reason_path: (*untyped) -> String
  def update_close_reason_path: (*untyped) -> String
  def new_close_reason_path: (*untyped) -> String
  def create_close_reason_path: (*untyped) -> String
  def tag_sets_path: (*untyped) -> String
  def global_tag_sets_path: (*untyped) -> String
  def tag_set_path: (*untyped) -> String
  def update_tag_set_path: (*untyped) -> String
  def licenses_path: (*untyped) -> String
  def new_license_path: (*untyped) -> String
  def create_license_path: (*untyped) -> String
  def edit_license_path: (*untyped) -> String
  def update_license_path: (*untyped) -> String
  def toggle_license_path: (*untyped) -> String
  def moderator_path: (*untyped) -> String
  def recently_deleted_posts_path: (*untyped) -> String
  def recent_comments_path: (*untyped) -> String
  def flag_queue_path: (*untyped) -> String
  def handled_flags_path: (*untyped) -> String
  def escalated_flags_path: (*untyped) -> String
  def destroy_user_path: (*untyped) -> String
  def mod_vote_summary_path: (*untyped) -> String
  def resolve_flag_path: (*untyped) -> String
  def escalate_flag_path: (*untyped) -> String
  def pinned_links_path: (*untyped) -> String
  def new_pinned_link_path: (*untyped) -> String
  def create_pinned_link_path: (*untyped) -> String
  def edit_pinned_link_path: (*untyped) -> String
  def update_pinned_link_path: (*untyped) -> String
  def questions_lottery_path: (*untyped) -> String
  def reactions_path: (*untyped) -> String
  def edit_reaction_path: (*untyped) -> String
  def update_reaction_path: (*untyped) -> String
  def new_reaction_path: (*untyped) -> String
  def create_reaction_path: (*untyped) -> String
  def add_reaction_path: (*untyped) -> String
  def retract_reaction_path: (*untyped) -> String
  def suggested_edit_path: (*untyped) -> String
  def suggested_edit_approve_path: (*untyped) -> String
  def suggested_edit_reject_path: (*untyped) -> String
  def new_post_path: (*untyped) -> String
  def new_response_path: (*untyped) -> String
  def new_category_post_path: (*untyped) -> String
  def create_post_path: (*untyped) -> String
  def create_response_path: (*untyped) -> String
  def create_category_post_path: (*untyped) -> String
  def search_path: (*untyped) -> String
  def promoted_posts_path: (*untyped) -> String
  def post_types_list_path: (*untyped) -> String
  def upload_path: (*untyped) -> String
  def save_draft_path: (*untyped) -> String
  def delete_draft_path: (*untyped) -> String
  def post_path: (*untyped) -> String
  def post_history_path: (*untyped) -> String
  def edit_post_path: (*untyped) -> String
  def update_post_path: (*untyped) -> String
  def close_post_path: (*untyped) -> String
  def reopen_post_path: (*untyped) -> String
  def delete_post_path: (*untyped) -> String
  def restore_post_path: (*untyped) -> String
  def change_category_path: (*untyped) -> String
  def post_comments_allowance_toggle_path: (*untyped) -> String
  def post_lock_path: (*untyped) -> String
  def post_unlock_path: (*untyped) -> String
  def post_feature_path: (*untyped) -> String
  def promote_post_path: (*untyped) -> String
  def remove_post_promotion_path: (*untyped) -> String
  def answer_post_path: (*untyped) -> String
  def policy_path: (*untyped) -> String
  def help_path: (*untyped) -> String
  def tags_path: (*untyped) -> String
  def two_factor_status_path: (*untyped) -> String
  def two_factor_enable_path: (*untyped) -> String
  def two_factor_enable_code_path: (*untyped) -> String
  def two_factor_confirm_enable_path: (*untyped) -> String
  def two_factor_disable_code_path: (*untyped) -> String
  def two_factor_confirm_disable_path: (*untyped) -> String
  def two_factor_send_disable_email_path: (*untyped) -> String
  def two_factor_disable_link_path: (*untyped) -> String
  def two_factor_confirm_disable_link_path: (*untyped) -> String
  def users_path: (*untyped) -> String
  def stack_redirect_path: (*untyped) -> String
  def claim_stack_content_path: (*untyped) -> String
  def qr_login_code_path: (*untyped) -> String
  def qr_login_path: (*untyped) -> String
  def users_me_path: (*untyped) -> String
  def user_preferences_path: (*untyped) -> String
  def set_user_preference_path: (*untyped) -> String
  def user_filters_path: (*untyped) -> String
  def default_filter_path: (*untyped) -> String
  def set_user_filter_path: (*untyped) -> String
  def delete_user_filter_path: (*untyped) -> String
  def notifications_path: (*untyped) -> String
  def edit_user_profile_path: (*untyped) -> String
  def update_user_profile_path: (*untyped) -> String
  def my_vote_summary_path: (*untyped) -> String
  def specific_auto_avatar_path: (*untyped) -> String
  def user_disconnect_sso_path: (*untyped) -> String
  def user_confirm_disconnect_sso_path: (*untyped) -> String
  def user_path: (*untyped) -> String
  def flag_history_path: (*untyped) -> String
  def user_activity_path: (*untyped) -> String
  def mod_user_path: (*untyped) -> String
  def user_posts_path: (*untyped) -> String
  def vote_summary_path: (*untyped) -> String
  def user_privileges_path: (*untyped) -> String
  def user_privilege_action_path: (*untyped) -> String
  def toggle_user_role_path: (*untyped) -> String
  def user_annotations_path: (*untyped) -> String
  def annotate_user_path: (*untyped) -> String
  def full_user_log_path: (*untyped) -> String
  def hellban_user_path: (*untyped) -> String
  def user_auto_avatar_path: (*untyped) -> String
  def read_notifications_path: (*untyped) -> String
  def read_all_notifications_path: (*untyped) -> String
  def create_vote_path: (*untyped) -> String
  def destroy_vote_path: (*untyped) -> String
  def convert_to_comment_path: (*untyped) -> String
  def new_flag_path: (*untyped) -> String
  def create_comment_thread_path: (*untyped) -> String
  def thread_pingable_path: (*untyped) -> String
  def create_comment_path: (*untyped) -> String
  def rename_comment_thread_path: (*untyped) -> String
  def restrict_comment_thread_path: (*untyped) -> String
  def unrestrict_comment_thread_path: (*untyped) -> String
  def comment_thread_followers_path: (*untyped) -> String
  def post_comments_path: (*untyped) -> String
  def follow_post_comments_path: (*untyped) -> String
  def comment_path: (*untyped) -> String
  def comment_thread_path: (*untyped) -> String
  def update_comment_path: (*untyped) -> String
  def delete_comment_path: (*untyped) -> String
  def undelete_comment_path: (*untyped) -> String
  def new_subscription_path: (*untyped) -> String
  def create_subscription_path: (*untyped) -> String
  def subscriptions_path: (*untyped) -> String
  def enable_subscription_path: (*untyped) -> String
  def destroy_subscription_path: (*untyped) -> String
  def users_report_path: (*untyped) -> String
  def subscriptions_report_path: (*untyped) -> String
  def posts_report_path: (*untyped) -> String
  def reactions_report_path: (*untyped) -> String
  def help_center_path: (*untyped) -> String
  def categories_path: (*untyped) -> String
  def new_category_path: (*untyped) -> String
  def create_category_path: (*untyped) -> String
  def set_default_filter_path: (*untyped) -> String
  def category_path: (*untyped) -> String
  def edit_category_path: (*untyped) -> String
  def update_category_path: (*untyped) -> String
  def edit_category_post_types_path: (*untyped) -> String
  def update_category_post_types_path: (*untyped) -> String
  def destroy_category_post_type_path: (*untyped) -> String
  def destroy_category_path: (*untyped) -> String
  def category_post_types_path: (*untyped) -> String
  def category_feed_path: (*untyped) -> String
  def category_tags_path: (*untyped) -> String
  def new_tag_path: (*untyped) -> String
  def create_tag_path: (*untyped) -> String
  def tag_path: (*untyped) -> String
  def tag_children_path: (*untyped) -> String
  def edit_tag_path: (*untyped) -> String
  def update_tag_path: (*untyped) -> String
  def rename_tag_path: (*untyped) -> String
  def select_tag_merge_path: (*untyped) -> String
  def merge_tag_path: (*untyped) -> String
  def nuke_tag_warning_path: (*untyped) -> String
  def nuke_tag_path: (*untyped) -> String
  def suggested_edits_queue_path: (*untyped) -> String
  def current_mod_warning_path: (*untyped) -> String
  def current_mod_warning_approve_path: (*untyped) -> String
  def mod_warning_log_path: (*untyped) -> String
  def new_mod_warning_path: (*untyped) -> String
  def create_mod_warning_path: (*untyped) -> String
  def lift_mod_warning_path: (*untyped) -> String
  def uploaded_path: (*untyped) -> String
  def dashboard_path: (*untyped) -> String
  def global_users_report_path: (*untyped) -> String
  def global_subs_report_path: (*untyped) -> String
  def global_posts_report_path: (*untyped) -> String
  def ads_path: (*untyped) -> String
  def codidact_ads_path: (*untyped) -> String
  def community_ads_path: (*untyped) -> String
  def random_question_ads_path: (*untyped) -> String
  def promoted_post_ads_path: (*untyped) -> String
  def specific_question_ads_path: (*untyped) -> String
  def specific_category_ads_path: (*untyped) -> String
  def tour_path: (*untyped) -> String
  def tour_q1_path: (*untyped) -> String
  def tour_q2_path: (*untyped) -> String
  def tour_q3_path: (*untyped) -> String
  def tour_more_path: (*untyped) -> String
  def tour_end_path: (*untyped) -> String
  def abilities_path: (*untyped) -> String
  def abilities_recalc_path: (*untyped) -> String
  def ability_path: (*untyped) -> String
  def donate_path: (*untyped) -> String
  def donation_intent_path: (*untyped) -> String
  def donation_success_path: (*untyped) -> String
  def donation_callback_path: (*untyped) -> String
  def initiate_oauth_path: (*untyped) -> String
  def approve_oauth_path: (*untyped) -> String
  def reject_oauth_path: (*untyped) -> String
  def oauth_token_path: (*untyped) -> String
  def oauth_apps_path: (*untyped) -> String
  def new_oauth_app_path: (*untyped) -> String
  def create_oauth_app_path: (*untyped) -> String
  def oauth_app_path: (*untyped) -> String
  def edit_oauth_app_path: (*untyped) -> String
  def update_oauth_app_path: (*untyped) -> String
  def deactivate_oauth_app_path: (*untyped) -> String
  def osd_path: (*untyped) -> String
  def fc_communities_path: (*untyped) -> String
  def rails_postmark_inbound_emails_path: (*untyped) -> String
  def rails_relay_inbound_emails_path: (*untyped) -> String
  def rails_sendgrid_inbound_emails_path: (*untyped) -> String
  def rails_mandrill_inbound_health_check_path: (*untyped) -> String
  def rails_mandrill_inbound_emails_path: (*untyped) -> String
  def rails_mailgun_inbound_emails_path: (*untyped) -> String
  def rails_conductor_inbound_emails_path: (*untyped) -> String
  def new_rails_conductor_inbound_email_path: (*untyped) -> String
  def edit_rails_conductor_inbound_email_path: (*untyped) -> String
  def rails_conductor_inbound_email_path: (*untyped) -> String
  def new_rails_conductor_inbound_email_source_path: (*untyped) -> String
  def rails_conductor_inbound_email_sources_path: (*untyped) -> String
  def rails_conductor_inbound_email_reroute_path: (*untyped) -> String
  def rails_conductor_inbound_email_incinerate_path: (*untyped) -> String
  def rails_service_blob_path: (*untyped) -> String
  def rails_service_blob_proxy_path: (*untyped) -> String
  def rails_blob_representation_path: (*untyped) -> String
  def rails_blob_representation_proxy_path: (*untyped) -> String
  def rails_disk_service_path: (*untyped) -> String
  def update_rails_disk_service_path: (*untyped) -> String
  def rails_direct_uploads_path: (*untyped) -> String
  def rails_representation_path: (*untyped) -> String
  def rails_blob_path: (*untyped) -> String
  def rails_storage_proxy_path: (*untyped) -> String
  def rails_storage_redirect_path: (*untyped) -> String
  def rails_mailers_url: (*untyped) -> String
  def rails_info_properties_url: (*untyped) -> String
  def rails_info_routes_url: (*untyped) -> String
  def rails_info_url: (*untyped) -> String
  def new_user_session_url: (*untyped) -> String
  def user_session_url: (*untyped) -> String
  def destroy_user_session_url: (*untyped) -> String
  def new_user_password_url: (*untyped) -> String
  def edit_user_password_url: (*untyped) -> String
  def user_password_url: (*untyped) -> String
  def cancel_user_registration_url: (*untyped) -> String
  def new_user_registration_url: (*untyped) -> String
  def edit_user_registration_url: (*untyped) -> String
  def user_registration_url: (*untyped) -> String
  def new_user_confirmation_url: (*untyped) -> String
  def user_confirmation_url: (*untyped) -> String
  def new_user_unlock_url: (*untyped) -> String
  def user_unlock_url: (*untyped) -> String
  def new_saml_user_session_url: (*untyped) -> String
  def saml_user_session_url: (*untyped) -> String
  def destroy_saml_user_session_url: (*untyped) -> String
  def metadata_user_session_url: (*untyped) -> String
  def idp_destroy_saml_user_session_url: (*untyped) -> String
  def login_verify_2fa_url: (*untyped) -> String
  def login_verify_code_url: (*untyped) -> String
  def sign_in_request_from_other_url: (*untyped) -> String
  def sign_in_return_from_base_url: (*untyped) -> String
  def after_sign_in_check_url: (*untyped) -> String
  def root_url: (*untyped) -> String
  def letter_opener_web_url: (*untyped) -> String
  def admin_url: (*untyped) -> String
  def admin_error_reports_url: (*untyped) -> String
  def site_settings_url: (*untyped) -> String
  def global_settings_url: (*untyped) -> String
  def site_setting_url: (*untyped) -> String
  def update_site_setting_url: (*untyped) -> String
  def soft_delete_user_url: (*untyped) -> String
  def admin_privileges_url: (*untyped) -> String
  def admin_privilege_url: (*untyped) -> String
  def admin_update_privilege_url: (*untyped) -> String
  def moderator_email_url: (*untyped) -> String
  def send_moderator_email_url: (*untyped) -> String
  def email_all_url: (*untyped) -> String
  def send_all_email_url: (*untyped) -> String
  def audit_log_url: (*untyped) -> String
  def new_site_url: (*untyped) -> String
  def create_site_url: (*untyped) -> String
  def setup_url: (*untyped) -> String
  def setup_save_url: (*untyped) -> String
  def stop_impersonating_url: (*untyped) -> String
  def verify_elevation_url: (*untyped) -> String
  def impersonate_url: (*untyped) -> String
  def start_impersonating_url: (*untyped) -> String
  def post_types_url: (*untyped) -> String
  def new_post_type_url: (*untyped) -> String
  def create_post_type_url: (*untyped) -> String
  def edit_post_type_url: (*untyped) -> String
  def update_post_type_url: (*untyped) -> String
  def close_reasons_url: (*untyped) -> String
  def close_reason_url: (*untyped) -> String
  def update_close_reason_url: (*untyped) -> String
  def new_close_reason_url: (*untyped) -> String
  def create_close_reason_url: (*untyped) -> String
  def tag_sets_url: (*untyped) -> String
  def global_tag_sets_url: (*untyped) -> String
  def tag_set_url: (*untyped) -> String
  def update_tag_set_url: (*untyped) -> String
  def licenses_url: (*untyped) -> String
  def new_license_url: (*untyped) -> String
  def create_license_url: (*untyped) -> String
  def edit_license_url: (*untyped) -> String
  def update_license_url: (*untyped) -> String
  def toggle_license_url: (*untyped) -> String
  def moderator_url: (*untyped) -> String
  def recently_deleted_posts_url: (*untyped) -> String
  def recent_comments_url: (*untyped) -> String
  def flag_queue_url: (*untyped) -> String
  def handled_flags_url: (*untyped) -> String
  def escalated_flags_url: (*untyped) -> String
  def destroy_user_url: (*untyped) -> String
  def mod_vote_summary_url: (*untyped) -> String
  def resolve_flag_url: (*untyped) -> String
  def escalate_flag_url: (*untyped) -> String
  def pinned_links_url: (*untyped) -> String
  def new_pinned_link_url: (*untyped) -> String
  def create_pinned_link_url: (*untyped) -> String
  def edit_pinned_link_url: (*untyped) -> String
  def update_pinned_link_url: (*untyped) -> String
  def questions_lottery_url: (*untyped) -> String
  def reactions_url: (*untyped) -> String
  def edit_reaction_url: (*untyped) -> String
  def update_reaction_url: (*untyped) -> String
  def new_reaction_url: (*untyped) -> String
  def create_reaction_url: (*untyped) -> String
  def add_reaction_url: (*untyped) -> String
  def retract_reaction_url: (*untyped) -> String
  def suggested_edit_url: (*untyped) -> String
  def suggested_edit_approve_url: (*untyped) -> String
  def suggested_edit_reject_url: (*untyped) -> String
  def new_post_url: (*untyped) -> String
  def new_response_url: (*untyped) -> String
  def new_category_post_url: (*untyped) -> String
  def create_post_url: (*untyped) -> String
  def create_response_url: (*untyped) -> String
  def create_category_post_url: (*untyped) -> String
  def search_url: (*untyped) -> String
  def promoted_posts_url: (*untyped) -> String
  def post_types_list_url: (*untyped) -> String
  def upload_url: (*untyped) -> String
  def save_draft_url: (*untyped) -> String
  def delete_draft_url: (*untyped) -> String
  def post_url: (*untyped) -> String
  def post_history_url: (*untyped) -> String
  def edit_post_url: (*untyped) -> String
  def update_post_url: (*untyped) -> String
  def close_post_url: (*untyped) -> String
  def reopen_post_url: (*untyped) -> String
  def delete_post_url: (*untyped) -> String
  def restore_post_url: (*untyped) -> String
  def change_category_url: (*untyped) -> String
  def post_comments_allowance_toggle_url: (*untyped) -> String
  def post_lock_url: (*untyped) -> String
  def post_unlock_url: (*untyped) -> String
  def post_feature_url: (*untyped) -> String
  def promote_post_url: (*untyped) -> String
  def remove_post_promotion_url: (*untyped) -> String
  def answer_post_url: (*untyped) -> String
  def policy_url: (*untyped) -> String
  def help_url: (*untyped) -> String
  def tags_url: (*untyped) -> String
  def two_factor_status_url: (*untyped) -> String
  def two_factor_enable_url: (*untyped) -> String
  def two_factor_enable_code_url: (*untyped) -> String
  def two_factor_confirm_enable_url: (*untyped) -> String
  def two_factor_disable_code_url: (*untyped) -> String
  def two_factor_confirm_disable_url: (*untyped) -> String
  def two_factor_send_disable_email_url: (*untyped) -> String
  def two_factor_disable_link_url: (*untyped) -> String
  def two_factor_confirm_disable_link_url: (*untyped) -> String
  def users_url: (*untyped) -> String
  def stack_redirect_url: (*untyped) -> String
  def claim_stack_content_url: (*untyped) -> String
  def qr_login_code_url: (*untyped) -> String
  def qr_login_url: (*untyped) -> String
  def users_me_url: (*untyped) -> String
  def user_preferences_url: (*untyped) -> String
  def set_user_preference_url: (*untyped) -> String
  def user_filters_url: (*untyped) -> String
  def default_filter_url: (*untyped) -> String
  def set_user_filter_url: (*untyped) -> String
  def delete_user_filter_url: (*untyped) -> String
  def notifications_url: (*untyped) -> String
  def edit_user_profile_url: (*untyped) -> String
  def update_user_profile_url: (*untyped) -> String
  def my_vote_summary_url: (*untyped) -> String
  def specific_auto_avatar_url: (*untyped) -> String
  def user_disconnect_sso_url: (*untyped) -> String
  def user_confirm_disconnect_sso_url: (*untyped) -> String
  def user_url: (*untyped) -> String
  def flag_history_url: (*untyped) -> String
  def user_activity_url: (*untyped) -> String
  def mod_user_url: (*untyped) -> String
  def user_posts_url: (*untyped) -> String
  def vote_summary_url: (*untyped) -> String
  def user_privileges_url: (*untyped) -> String
  def user_privilege_action_url: (*untyped) -> String
  def toggle_user_role_url: (*untyped) -> String
  def user_annotations_url: (*untyped) -> String
  def annotate_user_url: (*untyped) -> String
  def full_user_log_url: (*untyped) -> String
  def hellban_user_url: (*untyped) -> String
  def user_auto_avatar_url: (*untyped) -> String
  def read_notifications_url: (*untyped) -> String
  def read_all_notifications_url: (*untyped) -> String
  def create_vote_url: (*untyped) -> String
  def destroy_vote_url: (*untyped) -> String
  def convert_to_comment_url: (*untyped) -> String
  def new_flag_url: (*untyped) -> String
  def create_comment_thread_url: (*untyped) -> String
  def thread_pingable_url: (*untyped) -> String
  def create_comment_url: (*untyped) -> String
  def rename_comment_thread_url: (*untyped) -> String
  def restrict_comment_thread_url: (*untyped) -> String
  def unrestrict_comment_thread_url: (*untyped) -> String
  def comment_thread_followers_url: (*untyped) -> String
  def post_comments_url: (*untyped) -> String
  def follow_post_comments_url: (*untyped) -> String
  def comment_url: (*untyped) -> String
  def comment_thread_url: (*untyped) -> String
  def update_comment_url: (*untyped) -> String
  def delete_comment_url: (*untyped) -> String
  def undelete_comment_url: (*untyped) -> String
  def new_subscription_url: (*untyped) -> String
  def create_subscription_url: (*untyped) -> String
  def subscriptions_url: (*untyped) -> String
  def enable_subscription_url: (*untyped) -> String
  def destroy_subscription_url: (*untyped) -> String
  def users_report_url: (*untyped) -> String
  def subscriptions_report_url: (*untyped) -> String
  def posts_report_url: (*untyped) -> String
  def reactions_report_url: (*untyped) -> String
  def help_center_url: (*untyped) -> String
  def categories_url: (*untyped) -> String
  def new_category_url: (*untyped) -> String
  def create_category_url: (*untyped) -> String
  def set_default_filter_url: (*untyped) -> String
  def category_url: (*untyped) -> String
  def edit_category_url: (*untyped) -> String
  def update_category_url: (*untyped) -> String
  def edit_category_post_types_url: (*untyped) -> String
  def update_category_post_types_url: (*untyped) -> String
  def destroy_category_post_type_url: (*untyped) -> String
  def destroy_category_url: (*untyped) -> String
  def category_post_types_url: (*untyped) -> String
  def category_feed_url: (*untyped) -> String
  def category_tags_url: (*untyped) -> String
  def new_tag_url: (*untyped) -> String
  def create_tag_url: (*untyped) -> String
  def tag_url: (*untyped) -> String
  def tag_children_url: (*untyped) -> String
  def edit_tag_url: (*untyped) -> String
  def update_tag_url: (*untyped) -> String
  def rename_tag_url: (*untyped) -> String
  def select_tag_merge_url: (*untyped) -> String
  def merge_tag_url: (*untyped) -> String
  def nuke_tag_warning_url: (*untyped) -> String
  def nuke_tag_url: (*untyped) -> String
  def suggested_edits_queue_url: (*untyped) -> String
  def current_mod_warning_url: (*untyped) -> String
  def current_mod_warning_approve_url: (*untyped) -> String
  def mod_warning_log_url: (*untyped) -> String
  def new_mod_warning_url: (*untyped) -> String
  def create_mod_warning_url: (*untyped) -> String
  def lift_mod_warning_url: (*untyped) -> String
  def uploaded_url: (*untyped) -> String
  def dashboard_url: (*untyped) -> String
  def global_users_report_url: (*untyped) -> String
  def global_subs_report_url: (*untyped) -> String
  def global_posts_report_url: (*untyped) -> String
  def ads_url: (*untyped) -> String
  def codidact_ads_url: (*untyped) -> String
  def community_ads_url: (*untyped) -> String
  def random_question_ads_url: (*untyped) -> String
  def promoted_post_ads_url: (*untyped) -> String
  def specific_question_ads_url: (*untyped) -> String
  def specific_category_ads_url: (*untyped) -> String
  def tour_url: (*untyped) -> String
  def tour_q1_url: (*untyped) -> String
  def tour_q2_url: (*untyped) -> String
  def tour_q3_url: (*untyped) -> String
  def tour_more_url: (*untyped) -> String
  def tour_end_url: (*untyped) -> String
  def abilities_url: (*untyped) -> String
  def abilities_recalc_url: (*untyped) -> String
  def ability_url: (*untyped) -> String
  def donate_url: (*untyped) -> String
  def donation_intent_url: (*untyped) -> String
  def donation_success_url: (*untyped) -> String
  def donation_callback_url: (*untyped) -> String
  def initiate_oauth_url: (*untyped) -> String
  def approve_oauth_url: (*untyped) -> String
  def reject_oauth_url: (*untyped) -> String
  def oauth_token_url: (*untyped) -> String
  def oauth_apps_url: (*untyped) -> String
  def new_oauth_app_url: (*untyped) -> String
  def create_oauth_app_url: (*untyped) -> String
  def oauth_app_url: (*untyped) -> String
  def edit_oauth_app_url: (*untyped) -> String
  def update_oauth_app_url: (*untyped) -> String
  def deactivate_oauth_app_url: (*untyped) -> String
  def osd_url: (*untyped) -> String
  def fc_communities_url: (*untyped) -> String
  def rails_postmark_inbound_emails_url: (*untyped) -> String
  def rails_relay_inbound_emails_url: (*untyped) -> String
  def rails_sendgrid_inbound_emails_url: (*untyped) -> String
  def rails_mandrill_inbound_health_check_url: (*untyped) -> String
  def rails_mandrill_inbound_emails_url: (*untyped) -> String
  def rails_mailgun_inbound_emails_url: (*untyped) -> String
  def rails_conductor_inbound_emails_url: (*untyped) -> String
  def new_rails_conductor_inbound_email_url: (*untyped) -> String
  def edit_rails_conductor_inbound_email_url: (*untyped) -> String
  def rails_conductor_inbound_email_url: (*untyped) -> String
  def new_rails_conductor_inbound_email_source_url: (*untyped) -> String
  def rails_conductor_inbound_email_sources_url: (*untyped) -> String
  def rails_conductor_inbound_email_reroute_url: (*untyped) -> String
  def rails_conductor_inbound_email_incinerate_url: (*untyped) -> String
  def rails_service_blob_url: (*untyped) -> String
  def rails_service_blob_proxy_url: (*untyped) -> String
  def rails_blob_representation_url: (*untyped) -> String
  def rails_blob_representation_proxy_url: (*untyped) -> String
  def rails_disk_service_url: (*untyped) -> String
  def update_rails_disk_service_url: (*untyped) -> String
  def rails_direct_uploads_url: (*untyped) -> String
  def rails_representation_url: (*untyped) -> String
  def rails_blob_url: (*untyped) -> String
  def rails_storage_proxy_url: (*untyped) -> String
  def rails_storage_redirect_url: (*untyped) -> String
end
