module SearchHelper
  def search_posts: -> _ActiveRecord_Relation[Post, Integer]
  def filter_to_qualifiers: (Filter filter) -> Array[Hash[Symbol, untyped]]
  def active_filter: -> {default: bool, name: String?, min_score: Integer?, max_score: Integer?, min_answers: Integer?, max_answers: Integer?, include_tags: String?, exclude_tags: String?, status: String?}
  def params_to_qualifiers: -> Array[Hash[Symbol, untyped]]
  def parse_search: (String raw_search) -> {qualifiers: Array[String], search: String}
  def parse_qualifier_strings: (Array[String] qualifiers) -> Array[Hash[Symbol, untyped]]
  def qualifiers_to_sql: [T, PK] (Array[Hash[Symbol, untyped]] qualifiers, _ActiveRecord_Relation[T, PK] query) -> _ActiveRecord_Relation[T, PK]
  def numeric_value_sql: (String value) -> [String, String]
  def date_value_sql: (String value) -> [String, String, String]
end
