# TypeProf 0.21.7

# Classes
module TagsHelper
  def category_sort_tags: (untyped tags, untyped required_ids, untyped topic_ids, untyped moderator_ids) -> untyped
  def tag_classes: (untyped tag, untyped category) -> String
  def post_ids_for_tags: (untyped tag_ids) -> untyped
end
