name: Rubocop check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  rubocop:
    name: Rubocop checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq libmagickwand-dev
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
          bundler-cache: true
      - run: gem install rubocop-rake
      - run: bundle exec rubocop
