name: TypeScript check

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  typescript:
    name: TypeScript type checking
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install Node
      uses: actions/setup-node@v1
      with:
        node-version: 22
    - name: npm install
      run: npm install
    - name: tsc
      run: tsc
